// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project3.Models;

#nullable disable

namespace project3.Migrations
{
    [DbContext(typeof(DatasiteContext))]
    [Migration("20240127173653_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("project3.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"), 1L, 1);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Model")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Color = "Black",
                            Model = 2011,
                            Price = 200000.0,
                            Type = "Ford",
                            UserId = 1
                        },
                        new
                        {
                            CarId = 2,
                            Color = "Red",
                            Model = 2019,
                            Price = 100000.0,
                            Type = "BMW",
                            UserId = 2
                        },
                        new
                        {
                            CarId = 3,
                            Color = "White",
                            Model = 2013,
                            Price = 150000.0,
                            Type = "Scoda",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("project3.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Password")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Ahmad@gmail.com",
                            Name = "Ahmad",
                            Password = 123456
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Lujain@gmail.com",
                            Name = "Lujain",
                            Password = 123456
                        },
                        new
                        {
                            UserId = 3,
                            Email = "Mahmood@gmail.com",
                            Name = "Mahmood",
                            Password = 123456
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
